source(file.path(dirname(normalizePath(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value=TRUE)[1]), mustWork=FALSE)), "backend_common.R"))
opts <- parse_cli_args(); require_args(opts, c("vectors", "outdir"))
v <- readr::read_tsv(opts$vectors, show_col_types=FALSE); cols <- grep("^v[0-9]+$", names(v), value=TRUE)
if (!length(cols)) stop("vectors must contain v1, v2, ... columns", call.=FALSE)
M <- as.matrix(v[,cols]); signed <- colMeans(M); n <- nrow(M)
loo_range <- vapply(seq_len(ncol(M)), function(j) { x <- if(n < 2) NA_real_ else vapply(seq_len(n), function(i) mean(M[-i,j]), numeric(1)); diff(range(x, na.rm=TRUE)) }, numeric(1))
sign_stability <- vapply(seq_len(ncol(M)), function(j) { if(abs(signed[j]) < 1e-12) return(NA_real_); mean(sign(M[,j]) == sign(signed[j]) & M[,j] != 0) }, numeric(1))
write_tsv_safe(tibble(feature=sub("^v", "", cols), signed_mean_contribution=signed, mean_absolute_contribution=colMeans(abs(M)), participant_sign_stability=sign_stability, leave_one_participant_out_mean_range=loo_range, interpretation="descriptive signed directional contributors and participant stability; not biomarkers or causal features"), file.path(ensure_outdir(opts$outdir), "directional_feature_stability.tsv"))
