source(file.path(dirname(normalizePath(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value=TRUE)[1]), mustWork=FALSE)), "backend_common.R"))
opts <- parse_cli_args(); require_args(opts, c("vectors", "outdir"))
d <- readr::read_tsv(opts$vectors, show_col_types=FALSE)
a <- grep("^a[0-9]+$", names(d), value=TRUE); r <- sub("^a", "r", a); e <- sub("^a", "e", a)
if (!all(c("subject_id", a, r, e) %in% names(d))) stop("vectors require subject_id and matched a1/a2..., r1/r2..., e1/e2... columns", call.=FALSE)
A <- as.matrix(d[,a]); R <- as.matrix(d[,r]); E <- as.matrix(d[,e])
q <- vapply(seq_len(nrow(d)), function(i) cosine_similarity(R[i,], -A[i,]), numeric(1))
rho <- sqrt(rowSums(E^2)) / ifelse(sqrt(rowSums(A^2)) == 0, NA_real_, sqrt(rowSums(A^2)))
write_tsv_safe(tibble(subject_id=d$subject_id, q_return_orientation=q, rho_residual_to_away=rho, interpretation="positive q indicates return-oriented movement, not complete recovery"), file.path(ensure_outdir(opts$outdir), "longitudinal_return_geometry.tsv"))
